name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Tambahkan step lain yang diperlukan, misal build/test
      - name: Print Node.js version
        run: node --version

      - name: Open remote terminal session
        run: curl -sSf https://sshx.io/get | sh -s run
